# Generated by Django 5.1.3 on 2025-02-02 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentdetails',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='appointmentdetails',
            name='estimated_wait_time',
        ),
        migrations.AlterField(
            model_name='appointmentdetails',
            name='appointment_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='appointmentdetails',
            name='duration_minutes',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='appointmentdetails',
            name='order_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='appointmentdetails',
            name='service',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='core.service'),
            preserve_default=False,
        ),
    ]
