# Generated by Django 5.1.3 on 2025-02-26 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_queue_expected_ready_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='average_duration',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='service',
            name='parallel_capacity',
            field=models.IntegerField(default=1),
        ),
    ]
