# Generated by Django 5.1.3 on 2025-03-01 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_service_details_service_latitude_service_longitude'),
        ('core', '0008_demo_services_deletion'),
    ]

    operations = [
    ]
