# Generated by Django 5.1.3 on 2025-03-12 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_service_service_type_queuesequence_queuesequenceitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('employee', 'Employee'), ('admin', 'Admin')], max_length=50),
        ),
        migrations.CreateModel(
            name='ServiceAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_owner', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='core.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_services', to='core.user')),
            ],
            options={
                'verbose_name': 'Service Administrator',
                'verbose_name_plural': 'Service Administrators',
                'unique_together': {('user', 'service')},
            },
        ),
    ]
