# Generated by Django 5.1.3 on 2025-03-22 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='total_wait',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
