# Generated by Django 5.1.3 on 2025-03-31 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_feedback_total_wait'),
        ('core', 'update_service_parameters'),
    ]

    operations = [
    ]
