# Generated by Django 5.1.3 on 2025-03-26 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_feedback_total_wait'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='minimal_prep_time',
            field=models.IntegerField(default=5),
        ),
    ]
