# Generated by Django 5.1.3 on 2025-03-31 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_merge_20250331_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='minimal_prep_time',
            field=models.IntegerField(default=5),
        ),
    ]
