# Generated by Django 5.1.3 on 2025-03-31 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_service_minimal_prep_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('current_member_count', models.IntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_queues', to='core.service')),
            ],
            options={
                'verbose_name': 'Service Queue',
                'verbose_name_plural': 'Service Queues',
            },
        ),
        migrations.AddField(
            model_name='queue',
            name='service_queue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.servicequeue'),
        ),
    ]
