# Generated by Django 5.1.3 on 2025-03-31 23:02

from django.db import migrations

def link_queues_to_service_queues(apps, schema_editor):
    Queue = apps.get_model('core', 'Queue')
    ServiceQueue = apps.get_model('core', 'ServiceQueue')
    Service = apps.get_model('core', 'Service')
    
    # Get all services with active queues
    services_with_queues = Queue.objects.filter(
        status='pending', 
        is_active=True
    ).values_list('service', flat=True).distinct()
    
    for service_id in services_with_queues:
        service = Service.objects.get(id=service_id)
        
        # Create a service queue
        service_queue = ServiceQueue.objects.create(
            service=service,
            is_active=True,
            current_member_count=0
        )
        
        # Link all pending queues for this service to this service queue
        queue_members = Queue.objects.filter(
            service=service, 
            status='pending',
            is_active=True
        ).order_by('date_created')
        
        count = 0
        for queue in queue_members:
            queue.service_queue = service_queue
            queue.save()
            count += 1
        
        service_queue.current_member_count = count
        service_queue.save()


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0019_servicequeue_queue_service_queue'),
    ]

    operations = [
        migrations.RunPython(link_queues_to_service_queues),
    ]
