# Generated by Django 5.1.3 on 2025-04-03 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20250401_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='transferred_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferred_to', to='core.queue'),
        ),
        migrations.AlterField(
            model_name='queue',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('transferred', 'Transferred')], default='pending', max_length=50),
        ),
    ]
