# Generated by Django 5.1.3 on 2025-04-04 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_add_transferred_from_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='last_notification_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('frequency_minutes', models.IntegerField(default=5)),
                ('message_template', models.TextField(default='Your order is in queue. Position: {queue_position}, remaining time: {remaining_time} minutes.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to='core.service')),
            ],
        ),
    ]
