# Generated by Django 5.1.3 on 2025-04-11 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_appointmentdetails_actual_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='last_notified_position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
