# Generated by Django 5.1.3 on 2025-04-11 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_queue_last_notified_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentdetails',
            name='last_reminder_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointmentdetails',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
