# Generated by Django 5.1.3 on 2025-04-12 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_appointmentdetails_last_reminder_sent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointmentdetails',
            old_name='last_delay_minutes',
            new_name='delay_minutes',
        ),
        migrations.RemoveField(
            model_name='appointmentdetails',
            name='queue_status',
        ),
        migrations.RemoveField(
            model_name='appointmentdetails',
            name='reminder_sent',
        ),
        migrations.AddField(
            model_name='appointmentdetails',
            name='check_in_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointmentdetails',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('checked_in', 'Checked In'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('missed', 'Missed')], default='scheduled', max_length=50),
        ),
    ]
