# Generated by Django 5.1.3 on 2025-04-13 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_rename_last_delay_minutes_appointmentdetails_delay_minutes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeedetails',
            name='department',
        ),
        migrations.RemoveField(
            model_name='employeedetails',
            name='company',
        ),
        migrations.RemoveField(
            model_name='employeedetails',
            name='specialization',
        ),
        migrations.RemoveField(
            model_name='employeedetails',
            name='user',
        ),
        migrations.RemoveField(
            model_name='queue',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='queuesequenceitem',
            name='queue',
        ),
        migrations.RemoveField(
            model_name='queuesequenceitem',
            name='queue_sequence',
        ),
        migrations.RemoveField(
            model_name='queuesequenceitem',
            name='service',
        ),
        migrations.AddField(
            model_name='appointmentdetails',
            name='delay_reason',
            field=models.CharField(blank=True, help_text='Reason for the delay', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appointmentdetails',
            name='delay_set_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who set the delay', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='set_delays', to='core.user'),
        ),
        migrations.AddField(
            model_name='appointmentdetails',
            name='delay_set_time',
            field=models.DateTimeField(blank=True, help_text='When the delay was set', null=True),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Specialization',
        ),
        migrations.DeleteModel(
            name='EmployeeDetails',
        ),
        migrations.DeleteModel(
            name='QueueSequenceItem',
        ),
    ]
