# Generated by Django 5.1.3 on 2025-04-16 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_remove_employeedetails_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicewaittime',
            name='date_recorded',
            field=models.DateTimeField(),
        ),
    ]
