const styles = {
  container: {
    maxWidth: '900px',
    margin: '40px auto',
    padding: '30px',
    fontFamily: "'Inter', 'Helvetica Neue', Helvetica, Arial, sans-serif",
    background: 'rgba(255, 255, 255, 0.85)',
    backdropFilter: 'blur(8px)',
    borderRadius: '12px',
    boxShadow: '0 4px 20px rgba(0, 0, 0, 0.1)',
  },
  header: {
    textAlign: 'center',
    marginBottom: '30px',
    color: '#222',
    fontSize: '2rem',
    fontWeight: '600',
  },
  buttonGroup: {
    display: 'flex',
    justifyContent: 'center',
    gap: '20px',
    marginBottom: '30px',
  },
  button: {
    padding: '12px 25px',
    fontSize: '1rem',
    borderRadius: '8px',
    border: 'none',
    cursor: 'pointer',
    backgroundColor: '#007bff',
    color: '#fff',
    transition: 'all 0.3s ease',
  },
  buttonSecondary: {
    backgroundColor: '#28a745',
  },
  appointmentCard: {
    backgroundColor: '#fff',
    padding: '20px',
    margin: '15px 0',
    borderRadius: '10px',
    boxShadow: '0 4px 12px rgba(0, 0, 0, 0.1)',
    transition: 'transform 0.2s ease, box-shadow 0.2s ease',
    cursor: 'pointer',
  },
  appointmentTitle: {
    fontSize: '1.5rem',
    marginBottom: '12px',
    color: '#333',
    fontWeight: '500',
  },
  appointmentDetail: {
    margin: '8px 0',
    color: '#555',
    fontSize: '1rem',
  },
  removeButton: {
    marginLeft: '15px',
    backgroundColor: '#dc3545',
    color: '#fff',
    border: 'none',
    padding: '10px 20px',
    borderRadius: '6px',
    cursor: 'pointer',
    transition: 'background-color 0.3s ease, transform 0.2s ease',
  },
};

export default styles;
