const styles = {
  container: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    height: "100vh",
    backgroundColor: "#f3f4f6",
    margin: "0",
    padding: "0",
    overflow: "hidden",
    fontFamily: "'Roboto', sans-serif",
  },
  backButton: {
    position: "absolute",
    top: "20px",
    left: "20px",
    width: "50px",
    height: "50px",
    fontSize: "1.5rem",
    color: "#ffffff",
    backgroundColor: "#1d4ed8",
    border: "none",
    borderRadius: "50%",
    boxShadow: "0px 4px 8px rgba(0, 0, 0, 0.15)",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    transition: "all 0.3s ease",
  },
  backButtonHover: {
    backgroundColor: "#2563eb",
    transform: "scale(1.1)",
    boxShadow: "0px 6px 12px rgba(0, 0, 0, 0.2)",
  },
  scannerContainer: {
    position: "relative",
    width: "90vw",
    maxWidth: "320px",
    aspectRatio: "1 / 1",
    margin: "0 auto",
    backgroundColor: "#ffffff",
    borderRadius: "16px",
    boxShadow: "0 8px 16px rgba(0, 0, 0, 0.15)",
    overflow: "hidden",
  },
  qrScanner: {
    position: "absolute",
    top: "0",
    left: "0",
    width: "100%",
    height: "100%",
    objectFit: "cover",
    display: "block",
  },
  error: {
    color: "#dc2626",
    fontSize: "1rem",
    textAlign: "center",
    marginTop: "1rem",
    padding: "0.5rem",
    backgroundColor: "#fef2f2",
    border: "1px solid #fca5a5",
    borderRadius: "8px",
    width: "90%",
    maxWidth: "320px",
  },
};

export default styles;
